apiVersion: v1
kind: Pod
metadata:
   name: app
spec:
   containers:
   - name: flask-container01
     image: docker.io/ratoloko765/flask-boilerplate_app:latest 
     ports:
     - containerPort: 5000
